I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 23, in script
    d "Hi, Eileen!"
Exception: DynamicImage u'[t].png': could not find image. (u'4.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 23, in script
    d "Hi, Eileen!"
  File "/Users/dave/Desktop/RenPy/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Users/dave/Desktop/RenPy/renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "/Users/dave/Desktop/RenPy/renpy/character.py", line 1235, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/Users/dave/Desktop/RenPy/renpy/character.py", line 887, in do_display
    **display_args)
  File "/Users/dave/Desktop/RenPy/renpy/character.py", line 633, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/Users/dave/Desktop/RenPy/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/dave/Desktop/RenPy/renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/Users/dave/Desktop/RenPy/renpy/display/core.py", line 3735, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Users/dave/Desktop/RenPy/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "/Users/dave/Desktop/RenPy/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "/Users/dave/Desktop/RenPy/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "/Users/dave/Desktop/RenPy/renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "/Users/dave/Desktop/RenPy/renpy/display/core.py", line 570, in visit_all
    callback(self)
  File "/Users/dave/Desktop/RenPy/renpy/display/core.py", line 3735, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Users/dave/Desktop/RenPy/renpy/display/image.py", line 752, in per_interact
    self.find_target()
  File "/Users/dave/Desktop/RenPy/renpy/display/image.py", line 652, in find_target
    raise Exception(error)
Exception: DynamicImage u'[t].png': could not find image. (u'4.png')

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 7.4.9.2142
Thundy Games 1.0
Mon Oct 11 23:37:49 2021
